In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv")
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600
...,...,...,...,...,...,...,...
179,2018-03-05,175.210007,180.000000,174.270004,179.979996,179.979996,139852700
180,2018-03-12,180.289993,183.500000,177.619995,178.020004,178.020004,155417500
181,2018-03-19,177.320007,177.470001,164.940002,164.940002,164.940002,172670700
182,2018-03-26,168.070007,175.149994,165.190002,167.779999,167.779999,157898400
183,2018-03-29,167.804993,171.750000,166.899994,167.779999,167.779999,38398505

In [4]:
print(df.head())

         Date        Open        High         Low       Close   Adj Close  \
0  2014-09-29  100.589996  100.690002   98.040001   99.620003   93.514290
1  2014-10-06   99.949997  102.379997   98.309998  100.730003   94.556244
2  2014-10-13  101.330002  101.779999   95.180000   97.669998   91.683792
3  2014-10-20   98.320000  105.489998   98.220001  105.220001   98.771042
4  2014-10-27  104.849998  108.040001  104.699997  108.000000  101.380676

      Volume
0  142718700
1  280258200
2  358539800
3  358532900
4  220230600

In [6]:
print(df.shape)

(184, 7)

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       184 non-null    object
 1   Open       184 non-null    float64
 2   High       184 non-null    float64
 3   Low        184 non-null    float64
 4   Close      184 non-null    float64
 5   Adj Close  184 non-null    float64
 6   Volume     184 non-null    int64
dtypes: float64(5), int64(1), object(1)
memory usage: 10.2+ KB
None

In [8]:
print(df.describe())

             Open        High         Low       Close   Adj Close  \
count  184.000000  184.000000  184.000000  184.000000  184.000000
mean   127.040245  129.918098  124.340381  127.352663  123.838032
std     24.314449   24.577906   24.176736   24.356534   25.655569
min     92.389999   93.769997   89.470001   90.519997   87.796822
25%    108.882499  112.362499  106.152502  109.204998  105.301765
50%    118.895000  120.865002  116.870003  119.190002  114.999730
75%    144.935005  147.695000  143.227493  144.704994  143.039467
max    180.289993  183.500000  177.619995  179.979996  179.979996

             Volume
count  1.840000e+02
mean   1.910168e+08
std    8.160281e+07
min    3.839850e+07
25%    1.273706e+08
50%    1.744112e+08
75%    2.207755e+08
max    5.003630e+08

In [10]:
print(df.isnull().sum())

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [12]:
df['Daily Delta'] = df['Close'] - df['Open']

In [13]:
avg_open = df['Open'].mean()
avg_close = df['Close'].mean()

print(f"Average Open Price:  ${avg_open:.2f}")
print(f"Average Close Price: ${avg_close:.2f}")

Average Open Price:  $127.04
Average Close Price: $127.35

In [14]:
df= df.sort_values(by='Date')
df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Delta
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700,-0.969993
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200,0.780006
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800,-3.660004
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900,6.900001
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600,3.150002
...,...,...,...,...,...,...,...,...
179,2018-03-05,175.210007,180.000000,174.270004,179.979996,179.979996,139852700,4.769989
180,2018-03-12,180.289993,183.500000,177.619995,178.020004,178.020004,155417500,-2.269989
181,2018-03-19,177.320007,177.470001,164.940002,164.940002,164.940002,172670700,-12.380005
182,2018-03-26,168.070007,175.149994,165.190002,167.779999,167.779999,157898400,-0.290008
183,2018-03-29,167.804993,171.750000,166.899994,167.779999,167.779999,38398505,-0.024994